### ISSUE TITLE
icon is missing for icon size of 128, affecting versions [2.1.0 - 2.1.3]

### ISSUE THREAD

**Issue by clampi** [shanemadden/factorio-deadlock-beltboxes-loaders#3]
Using the API to add stacking support for an item with icon_size=128 causes the following error:
22.285 Error AtlasSystem.cpp:1206: File not found: __deadlock-beltboxes-loaders__/graphics/icons/arrow-d-128.png

Sure enough, the icon is missing. In 2.0.10 (before the mod graphical update) was present. The internal code is still supporting icon_size=128, is just the resource that's missing.

**Comment by shanemadden** [comment]
Thanks, I'll get this fixed!

**Comment by shanemadden** [comment]
Should be fixed in 2.1.4, let me know if not!
